// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_open
SEXP cpp_open();
RcppExport SEXP _vProlog_cpp_open() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_open());
    return rcpp_result_gen;
END_RCPP
}
// cpp_close
void cpp_close(SEXP ptr);
RcppExport SEXP _vProlog_cpp_close(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    cpp_close(ptr);
    return R_NilValue;
END_RCPP
}
// cpp_consult
bool cpp_consult(SEXP ptr, std::string filename);
RcppExport SEXP _vProlog_cpp_consult(SEXP ptrSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_consult(ptr, filename));
    return rcpp_result_gen;
END_RCPP
}
// cpp_eval
bool cpp_eval(SEXP ptr, std::string expr);
RcppExport SEXP _vProlog_cpp_eval(SEXP ptrSEXP, SEXP exprSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type expr(exprSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_eval(ptr, expr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_query
bool cpp_query(SEXP ptr, std::string goal);
RcppExport SEXP _vProlog_cpp_query(SEXP ptrSEXP, SEXP goalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type goal(goalSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_query(ptr, goal));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vProlog_cpp_open", (DL_FUNC) &_vProlog_cpp_open, 0},
    {"_vProlog_cpp_close", (DL_FUNC) &_vProlog_cpp_close, 1},
    {"_vProlog_cpp_consult", (DL_FUNC) &_vProlog_cpp_consult, 2},
    {"_vProlog_cpp_eval", (DL_FUNC) &_vProlog_cpp_eval, 2},
    {"_vProlog_cpp_query", (DL_FUNC) &_vProlog_cpp_query, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_vProlog(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
