# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_open <- function() {
    .Call(`_vProlog_cpp_open`)
}

cpp_consult <- function(ptr, filename) {
    .Call(`_vProlog_cpp_consult`, ptr, filename)
}

cpp_eval <- function(ptr, expr) {
    .Call(`_vProlog_cpp_eval`, ptr, expr)
}

cpp_query <- function(ptr, goal) {
    .Call(`_vProlog_cpp_query`, ptr, goal)
}

